import { ProductAnalysisItem, Transaction, DashboardMetrics, TrendDayData, AIInsight, Experiment } from '@/types';

export const DEMO_USER_ID = 'demo-user-pak-budi';

export const DEMO_PRODUCTS: ProductAnalysisItem[] = [
  {
    id: 'prod-demo-bawang',
    user_id: DEMO_USER_ID,
    name: 'Bawang Merah Brebes',
    unit: 'kg',
    cost_price: 30000,
    selling_price: 40000,
    margin_percentage: 25,
    action_category: 'dorong',
    avg_daily_volume: 15,
    total_revenue_7d: 4200000,
    remaining_stock: 24,
    is_stock_low: false,
    image_url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod-demo-cabai',
    user_id: DEMO_USER_ID,
    name: 'Cabai Rawit Merah',
    unit: 'kg',
    cost_price: 45000,
    selling_price: 54000,
    margin_percentage: 17,
    action_category: 'perbaiki',
    avg_daily_volume: 8,
    total_revenue_7d: 3024000,
    remaining_stock: 6,
    is_stock_low: false,
    image_url: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod-demo-tomat',
    user_id: DEMO_USER_ID,
    name: 'Tomat Buah Segar',
    unit: 'kg',
    cost_price: 10000,
    selling_price: 15000,
    margin_percentage: 33,
    action_category: 'dorong',
    avg_daily_volume: 12,
    total_revenue_7d: 1260000,
    remaining_stock: 28,
    is_stock_low: false,
    image_url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'prod-demo-kangkung',
    user_id: DEMO_USER_ID,
    name: 'Kangkung Segar',
    unit: 'ikat',
    cost_price: 2000,
    selling_price: 3500,
    margin_percentage: 43,
    action_category: 'dorong',
    avg_daily_volume: 30,
    total_revenue_7d: 735000,
    remaining_stock: 35,
    is_stock_low: false,
  },
  {
    id: 'prod-demo-ayam',
    user_id: DEMO_USER_ID,
    name: 'Ayam Potong Segar',
    unit: 'kg',
    cost_price: 32000,
    selling_price: 38000,
    margin_percentage: 16,
    action_category: 'perbaiki',
    avg_daily_volume: 10,
    total_revenue_7d: 2660000,
    remaining_stock: 8,
    is_stock_low: false,
  },
  {
    id: 'prod-demo-telur',
    user_id: DEMO_USER_ID,
    name: 'Telur Ayam Negeri',
    unit: 'kg',
    cost_price: 26000,
    selling_price: 29000,
    margin_percentage: 10,
    action_category: 'perbaiki',
    avg_daily_volume: 20,
    total_revenue_7d: 4060000,
    remaining_stock: 45,
    is_stock_low: false,
  },
];

const now = new Date();
const todayISO = now.toISOString();
const yesterdayISO = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString();

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-demo-01',
    user_id: DEMO_USER_ID,
    type: 'income',
    transaction_date: todayISO,
    source: 'voice',
    raw_voice_text: 'Jual bawang merah dua kilo delapan puluh ribu',
    total_amount: 80000,
    items: [
      {
        id: 'txi-demo-01',
        transaction_id: 'tx-demo-01',
        product_id: 'prod-demo-bawang',
        product_name: 'Bawang Merah Brebes',
        quantity: 2,
        unit: 'kg',
        unit_price: 40000,
        subtotal: 80000,
      },
    ],
  },
  {
    id: 'tx-demo-02',
    user_id: DEMO_USER_ID,
    type: 'income',
    transaction_date: todayISO,
    source: 'voice',
    raw_voice_text: 'Jual cabai rawit merah satu kilo lima puluh empat ribu',
    total_amount: 54000,
    items: [
      {
        id: 'txi-demo-02',
        transaction_id: 'tx-demo-02',
        product_id: 'prod-demo-cabai',
        product_name: 'Cabai Rawit Merah',
        quantity: 1,
        unit: 'kg',
        unit_price: 54000,
        subtotal: 54000,
      },
    ],
  },
  {
    id: 'tx-demo-03',
    user_id: DEMO_USER_ID,
    type: 'income',
    transaction_date: todayISO,
    source: 'manual',
    raw_voice_text: 'Jual tomat buah segar tiga kilo empat puluh lima ribu',
    total_amount: 45000,
    items: [
      {
        id: 'txi-demo-03',
        transaction_id: 'tx-demo-03',
        product_id: 'prod-demo-tomat',
        product_name: 'Tomat Buah Segar',
        quantity: 3,
        unit: 'kg',
        unit_price: 15000,
        subtotal: 45000,
      },
    ],
  },
  {
    id: 'tx-demo-04',
    user_id: DEMO_USER_ID,
    type: 'expense',
    transaction_date: todayISO,
    source: 'voice',
    raw_voice_text: 'Beli stok sayur mayur pasar induk seratus lima puluh ribu',
    total_amount: 150000,
    items: [
      {
        id: 'txi-demo-04',
        transaction_id: 'tx-demo-04',
        product_id: 'prod-demo-kangkung',
        product_name: 'Kangkung Segar',
        quantity: 30,
        unit: 'ikat',
        unit_price: 2000,
        subtotal: 60000,
      },
      {
        id: 'txi-demo-04b',
        transaction_id: 'tx-demo-04',
        product_id: 'prod-demo-tomat',
        product_name: 'Tomat Buah Segar',
        quantity: 9,
        unit: 'kg',
        unit_price: 10000,
        subtotal: 90000,
      },
    ],
  },
  {
    id: 'tx-demo-05',
    user_id: DEMO_USER_ID,
    type: 'income',
    transaction_date: yesterdayISO,
    source: 'voice',
    raw_voice_text: 'Jual ayam potong dua kilo tujuh puluh enam ribu',
    total_amount: 76000,
    items: [
      {
        id: 'txi-demo-05',
        transaction_id: 'tx-demo-05',
        product_id: 'prod-demo-ayam',
        product_name: 'Ayam Potong Segar',
        quantity: 2,
        unit: 'kg',
        unit_price: 38000,
        subtotal: 76000,
      },
    ],
  },
  {
    id: 'tx-demo-06',
    user_id: DEMO_USER_ID,
    type: 'income',
    transaction_date: yesterdayISO,
    source: 'manual',
    raw_voice_text: 'Jual telur ayam tiga kilo delapan puluh tujuh ribu',
    total_amount: 87000,
    items: [
      {
        id: 'txi-demo-06',
        transaction_id: 'tx-demo-06',
        product_id: 'prod-demo-telur',
        product_name: 'Telur Ayam Negeri',
        quantity: 3,
        unit: 'kg',
        unit_price: 29000,
        subtotal: 87000,
      },
    ],
  },
];

export const DEMO_DASHBOARD_METRICS: DashboardMetrics = {
  today_income: 179000,
  today_income_change: 12.5,
  today_expense: 150000,
  today_expense_change: -8.0,
  today_profit: 48500,
  today_profit_change: 15.2,
  today_margin: 27,
  today_margin_change: 2.1,
};

export const DEMO_TREND_DATA: TrendDayData[] = [
  { date: '2026-09-05', dayName: 'Sen', income: 420000, expense: 310000 },
  { date: '2026-09-06', dayName: 'Sel', income: 510000, expense: 380000 },
  { date: '2026-09-07', dayName: 'Rab', income: 480000, expense: 320000 },
  { date: '2026-09-08', dayName: 'Kam', income: 530000, expense: 410000 },
  { date: '2026-09-09', dayName: 'Jum', income: 620000, expense: 450000 },
  { date: '2026-09-10', dayName: 'Sab', income: 750000, expense: 520000 },
  { date: '2026-09-11', dayName: 'Min', income: 179000, expense: 150000 },
];

export const DEMO_PRIMARY_INSIGHT: AIInsight = {
  id: 'insight-demo-01',
  user_id: DEMO_USER_ID,
  product_id: 'prod-demo-cabai',
  product_name: 'Cabai Rawit Merah',
  severity: 'yellow',
  message: 'Keuntungan Cabai Rawit Merah (17%) di bawah target aman 20%. Coba naikkan harga jual dari Rp54.000 ke Rp56.000/kg atau pantau via Coba & Pantau.',
  has_quick_action: true,
  created_at: todayISO,
};

export const DEMO_EXPERIMENTS: Experiment[] = [
  {
    id: 'exp-demo-01',
    user_id: DEMO_USER_ID,
    product_id: 'prod-demo-cabai',
    product_name: 'Cabai Rawit Merah',
    title: 'Eksperimen Harga Cabai Rawit Merah',
    status: 'running',
    baseline_metric: {
      price: 54000,
      margin: 17,
      daily_volume: 8,
    },
    target_metric: {
      price: 56000,
      margin: 20,
      daily_volume: 8,
    },
    started_at: todayISO,
  },
];
